# Spring Boot 설정
spring:
  kafka:
    producer:
      bootstrap-servers: 129.154.222.27:9092
  application:
    name: nbbang-user, common, jwt-common, member-datasource     # common 공통 프로퍼티 불러오기
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8197
  rabbitmq:
    host: 129.154.222.27
    port: 5672
    username: nbbang
    password: nbbang-dev!@#
  main:
    allow-bean-definition-overriding: true
#  sleuth:
#    sampler:
#      probability: 1.0
#  zipkin:
#    base-url: http://localhost:9411
#    kafka:
#      topic: 'new-member-register'


# 서버 설정
server:
  port: 9000
  servlet:
    context-path: /nbbang-user

# acutator
management:
  endpoints:
    web:
      exposure:
        include: busrefresh

# 키스토어 복호화
encrypt:
  key-store:
#    location: file:///home/ubuntu/nbbang/key/nbbang-config.jks
    location: file:///Users/zayson/Desktop/Zayson Project/엔빵/nbbang-config.jks
    password: config-access
    alias: nbbang-config-key

# 소셜 연동해제
sns:
  kakao:
    client-id: 7b5f1de64dc43b926149cad3b0dc4882
    client-secret: SBTDMjD1EGdc9cTUiAPABHSdPmCC8F57
    regenerate-token-uri: https://kauth.kakao.com/oauth/token
    unlink-uri: https://kapi.kakao.com/v1/user/unlink
  google:
    client:
      id: 126433517317-km3kks28bium4h714ous7o09059a4p7c.apps.googleusercontent.com
      secret: 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
    revoke:
      uri: https://oauth2.googleapis.com/revoke
    token:
      uri: https://oauth2.googleapis.com/token
