# Spring Boot 설정
spring:
  application:
    name: nbbang-user, common, jwt-common, member-datasource     # common 공통 프로퍼티 불러오기
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8197
  rabbitmq:
    host: 129.154.222.27
    port: 5672
    username: nbbang
    password: nbbang-dev!@#
  main:
    allow-bean-definition-overriding: true
# 서버 설정
server:
  port: 9000
  servlet:
    context-path: /nbbang-user

# acutator
management:
  endpoints:
    web:
      exposure:
        include: busrefresh


#
##aes256 key값
#aes.key=akf39dk2lskcv4uc834zuwi1jcnma2f3
#
#imp.token.url=https://api.iamport.kr/users/getToken
#imp.billing.url=https://api.iamport.kr/subscribe/customers
#imp.client.key=4738003304274604
#imp.client.secret=15dcccbe238c258980c02f4b4fd7d10060887cd418bc0ad086f36873856b7746c62d7739eef780d1

#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
