# Spring Boot 설정
spring:
  application:
    name: nbbang-user, common, jwt-common, member-datasource     # common 공통 프로퍼티 불러오기
  profiles:
    active: prod
  config:
    import: optional:configserver:http://129.154.222.27:8197
  rabbitmq:
    host: 129.154.222.27
    port: 5672
    username: nbbang
    password: nbbang-dev!@#
  main:
    allow-bean-definition-overriding: true
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    kafka:
      topic: 'new-member-register'


# 서버 설정
server:
  port: 9000
  servlet:
    context-path: /nbbang-user

# acutator
management:
  endpoints:
    web:
      exposure:
        include: busrefresh

# 키스토어 복호화
encrypt:
  key-store:
    location: file:///home/ubuntu/nbbang/key/nbbang-config.jks
    password: config-access
    alias: nbbang-config-key
